name: test

on:
  pull_request:
      branches:
        - main
  push:
    branches:
      - main
      - feature/*

env:
  PLUGIN_NAME: obsidian-simple-day-planner

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package.json') }}
        restore-keys: npm-
    - name: install dependencies
      run: npm install
    - name: test
      run: npm test
